Implemente la funcionalidad para agregar los productos en el archivo …
juanda19oficial/MiniProyecto4 pull request #1
Opened 2024-06-15 22:19 UTC by juanda19oficial

…de texto y el nodo

2024-06-15 23:56 UTC, Vane2005 commented on src/filesManagament/manejoArchivos.java
> +            writer.write("\r"+codigo + "," + nombre + "," + cantidad);
organizar el orden de nombre y cantidad

2024-06-15 23:57 UTC, Vane2005 requested changes
hacer el cambio solicitado, por otro lado sería conveniente hacer validaciones cuando se ingrese un código ya existente

2024-06-16 01:44 UTC, juanda19oficial reviewed
@Vane2005 Ya hice los cambios sugeridos :)

2024-06-16 17:59 UTC, Vane2005 approved these changes
Todo funciona bien

2024-06-16 17:59 UTC, merged